---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - test
  dependencies:
    - name: java
      repo: git
      source: https://github.com/extenda-saltstack-formulas/java-oracle-formula.git
  grains:
    customer: auc
  pillars_from_directories:
    - pillar-data

platforms:
  - name: centos/7

suites:
  - name: epson
    provisioner:
      grains:
        device: epsonprinter
      state_top:
        base:
          '*':
              - epson.epson_javapos_adk

  - name: epsonfiscal
    provisioner:
      grains:
        device: uposfiscalprinter
      state_top:
        base:
          '*':
              - epsonfiscal.epsonfiscal_javapos

  - name: fujitsu
    provisioner:
      grains:
        device: fujitsuprinter
      state_top:
        base:
          '*':
              - fujitsu.fujitsu_javapos

  - name: datalogic
    provisioner:
      grains:
        device: gryphon-gd4400
      state_top:
        base:
          '*':
              - datalogic.datalogic_javapos_dls

  - name: diebold-nixdorf
    provisioner:
      grains:
        device: diebold-nixdorf
      state_top:
        base:
          '*':
              - diebold-nixdorf.diebold-nixdorf_javapos

  - name: ncr
    provisioner:
      grains:
        device: ncr
      state_top:
        base:
          '*':
              - ncr.ncr_scanner_scale
